"""empty message

Revision ID: 20efd840bb47
Revises: 36cdd252785f
Create Date: 2023-05-10 23:06:42.707892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20efd840bb47'
down_revision = '36cdd252785f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('singer', sa.String(length=100), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=False),
    sa.Column('score', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_song',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'song_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', mysql.VARCHAR(length=500), nullable=True))

    op.drop_table('user_song')
    op.drop_table('song')
    # ### end Alembic commands ###
