"""empty message

Revision ID: 8577eae2ee5b
Revises: 16757f531439
Create Date: 2023-05-11 12:50:32.701003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8577eae2ee5b'
down_revision = '16757f531439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval', sa.Integer(), nullable=False))
        batch_op.drop_column('join_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_time', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('interval')

    # ### end Alembic commands ###
