"""empty message

Revision ID: 8812661b260d
Revises: c15f2038b918
Create Date: 2023-05-13 15:06:44.736623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8812661b260d'
down_revision = 'c15f2038b918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_song', schema=None) as batch_op:
        batch_op.drop_constraint('user_song_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_song_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'song', ['song_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_song', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_song_ibfk_1', 'song', ['song_id'], ['id'])
        batch_op.create_foreign_key('user_song_ibfk_2', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
