"""empty message

Revision ID: ec5575375e6c
Revises: 8577eae2ee5b
Create Date: 2023-05-11 19:47:21.431789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec5575375e6c'
down_revision = '8577eae2ee5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(precision=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=sa.Float(precision=1),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
